name: Staging deployment

on:
  pull_request:
    types: [labeled]

jobs:
  build-and-deploy:
    if: contains(github.event.pull_request.labels.*.name, 'stage')
    runs-on: ubuntu-latest

    name: Deploy app to Azure
    steps:
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Checkout Github Action' 
        uses: actions/checkout@master

      - name: Setup Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies and run tests
        run: |
          npm install
          npm run test --if-present

      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with:
          app-name: gh-workshop

      - name: Azure logout
        run: |
          az logout
